<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import Breadcrumbs from './Breadcrumbs.vue'
import { EditorState } from '@codemirror/state'
import { drawSelection, dropCursor, EditorView, keymap, lineNumbers } from '@codemirror/view'
import { defaultKeymap, history, historyKeymap, indentWithTab } from '@codemirror/commands'
import { HighlightStyle, indentOnInput, syntaxHighlighting } from '@codemirror/language'
import { tags as t } from '@lezer/highlight'
import { javascript as javascriptMode } from '@codemirror/lang-javascript'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { PdfDoc, createTheme, useFonts } from '../../../src/index'
import { loadPdf } from '../../../src/lib/edit'
import { fromHex } from '../../../src/lib/utils/color-utils'
import { applyEdits, widgetSandbox } from './sandbox'

/**
 * Live PDF-editing workbench for the docs playground.
 *
 * The editor holds the body of a plain-JS function receiving `pages` — the
 * loaded document's pages as Page widgets. Code overlays widgets with
 * `pages[i].add([...])` and restructures by mutating the array; factories
 * and helpers are injected as parameters (same sandbox contract as the
 * widget playground), evaluated with `new Function` on every debounced
 * render. The sample document is synthesized with pdf-lib — no binary
 * assets — and a file input swaps in the visitor's own PDF.
 * Mount inside <ClientOnly> — rendering touches browser APIs.
 */

const SAMPLE_CODE = `// PDF editing playground — edit the code; the PDF re-renders as you type.
//
// \`pages\` holds the loaded document's pages as Page widgets, sized from the
// file. Overlay widgets with pages[i].add([...]) — they paint on top of the
// original content. Restructure by mutating the array (splice/push).
// Widget factories (Page, Text, Row, Column, Container, FixedContainer,
// HLine, Table, …) plus \`theme\` and \`fromHex\` are already in scope — plain
// JavaScript, no imports or types needed.

// A review stamp on page one — flow placement from the top of the page.
pages[0].add([
  Text([{ text: 'REVIEWED', bold: true, color: fromHex('#B45309') }], { size: 26 }),
  HLine({ thickness: 2, color: fromHex('#B45309') }),
  Text('Approved by pdf-kalem on ' + new Date().toLocaleDateString(), {
    size: 10,
    color: fromHex('#6b7280'),
  }),
]);

// Absolute placement: a corner note pinned to the page's bottom-right.
pages[0].add([
  FixedContainer({
    bottom: 28,
    right: 28,
    children: [Text('Edited with pdf-kalem', { size: 9, color: fromHex('#92400E') })],
  }),
]);

// Page two: mark it confidential, top-left.
pages[1].add([
  FixedContainer({
    top: 24,
    left: 24,
    children: [Text('CONFIDENTIAL', { size: 12, color: fromHex('#b91c1c') })],
  }),
]);

// Restructure: pages is a plain array — uncomment to try.
// pages.splice(2, 1);                       // drop the appendix
// pages.reverse();                          // reorder
// pages.push(Page({                         // append a generated page
//   children: [Text('Generated by pdf-kalem', { size: 14 })],
// }));
`

const theme = createTheme({
  fonts: {
    body: 'inter',
    code: 'mono',
  },
  colors: {
    ink: fromHex('#1f2937'),
    muted: fromHex('#6b7280'),
  },
  text: {
    body: { font: 'body', size: 11, color: 'ink' },
    h2: { font: 'body', size: 16, color: 'ink' },
  },
})

/** A two-page fake "memo" synthesized with pdf-lib — something to edit. */
async function makeSamplePdf(): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const helv = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const one = doc.addPage([612, 792])
  one.drawRectangle({ x: 0, y: 712, width: 612, height: 80, color: rgb(0.96, 0.94, 0.9) })
  one.drawText('Q3 QUARTERLY MEMO', { x: 48, y: 744, size: 22, font: bold, color: rgb(0.12, 0.16, 0.22) })
  one.drawText('Internal distribution only', { x: 48, y: 724, size: 10, font: helv, color: rgb(0.42, 0.45, 0.5) })

  const meta = [
    ['From', 'Operations'],
    ['To', 'All team leads'],
    ['Date', 'October 9, 2026'],
    ['Re', 'Q3 results and Q4 planning'],
  ]
  meta.forEach(([label, value], i) => {
    const y = 660 - i * 18
    one.drawText(label.toUpperCase(), { x: 48, y, size: 8, font: bold, color: rgb(0.55, 0.57, 0.6) })
    one.drawText(value, { x: 130, y, size: 10, font: helv, color: rgb(0.12, 0.16, 0.22) })
  })

  const body = [
    'Q3 closed ahead of plan. Revenue grew 14% quarter over quarter, driven',
    'by renewals in the enterprise segment and the two launches in June.',
    'Churn held flat at 2.1% despite the pricing change in August.',
    '',
    'For Q4 the priority is onboarding: activation within the first week',
    'doubles the odds of renewal, and the current flow loses too many teams',
    'between signup and first document. Expect a proposal from the product',
    'group by mid-October.',
  ]
  body.forEach((line, i) => {
    one.drawText(line, { x: 48, y: 560 - i * 16, size: 10, font: helv, color: rgb(0.2, 0.23, 0.28) })
  })

  one.drawLine({
    start: { x: 48, y: 120 },
    end: { x: 380, y: 120 },
    thickness: 0.75,
    color: rgb(0.7, 0.72, 0.75),
  })
  one.drawText('Signature', { x: 48, y: 100, size: 8, font: helv, color: rgb(0.55, 0.57, 0.6) })

  const two = doc.addPage([612, 792])
  two.drawText('APPENDIX: FIGURES', { x: 48, y: 720, size: 16, font: bold, color: rgb(0.12, 0.16, 0.22) })

  const rows = [
    ['Segment', 'Q2', 'Q3', 'Change'],
    ['Enterprise', '$412k', '$486k', '+18%'],
    ['Mid-market', '$238k', '$251k', '+5%'],
    ['Self-serve', '$96k', '$104k', '+8%'],
  ]
  rows.forEach((row, r) => {
    const y = 670 - r * 24
    row.forEach((cell, c) => {
      two.drawText(cell, {
        x: 48 + c * 140,
        y,
        size: 10,
        font: r === 0 ? bold : helv,
        color: r === 0 ? rgb(0.55, 0.57, 0.6) : rgb(0.2, 0.23, 0.28),
      })
    })
    two.drawLine({
      start: { x: 48, y: y - 8 },
      end: { x: 48 + 3 * 140 + 80, y: y - 8 },
      thickness: 0.5,
      color: rgb(0.85, 0.86, 0.88),
    })
  })

  return doc.save()
}

// --- State -------------------------------------------------------------------

const editorEl = ref<HTMLDivElement>()
const frameEl = ref<HTMLIFrameElement>()
const badge = ref('…')
const error = ref('')
const downloadHref = ref('')
const fileName = ref('sample document')

const view = ref<EditorView>()
let objectUrl: string | undefined
let timer: ReturnType<typeof setTimeout> | undefined
let sampleBytes: Uint8Array | undefined
// Assigned after useFonts resolves; undefined keeps builtin fonts.
let fonts: Awaited<ReturnType<typeof useFonts>> | undefined

// --- Rendering ----------------------------------------------------------------

async function render(): Promise<void> {
  if (!view.value || !sampleBytes) return
  badge.value = 'rendering…'
  try {
    // Fresh load per render: LoadedPage state (overlays) lives on the widget
    // tree, so re-loading the bytes keeps repeated renders idempotent.
    const pdf = await loadPdf(sampleBytes, { theme, fonts })
    applyEdits(view.value.state.doc.toString(), widgetSandbox({ theme }), pdf.pages)

    const doc = new PdfDoc({
      theme,
      fonts,
      meta: {
        title: 'pdf-kalem editing playground',
        creator: 'pdf-kalem',
        producer: 'pdf-lib',
      },
      children: pdf.pages,
    })

    const blob = await doc.getBlob()
    const pageCount = await doc.getPageCount()

    if (objectUrl) URL.revokeObjectURL(objectUrl)
    objectUrl = URL.createObjectURL(blob)
    if (frameEl.value) frameEl.value.src = objectUrl
    downloadHref.value = objectUrl
    error.value = ''
    badge.value = `${pageCount} page${pageCount === 1 ? '' : 's'}`
  } catch (err) {
    console.error('editing playground: render failed', err)
    error.value = err instanceof Error ? err.message : String(err)
    badge.value = 'render failed'
  }
}

function schedule(): void {
  if (timer) clearTimeout(timer)
  timer = setTimeout(() => {
    void render()
  }, 400)
}

function reset(): void {
  if (!view.value) return
  view.value.dispatch({ changes: { from: 0, to: view.value.state.doc.length, insert: SAMPLE_CODE } })
  void render()
}

async function loadFile(event: Event): Promise<void> {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  sampleBytes = new Uint8Array(await file.arrayBuffer())
  fileName.value = file.name
  await render()
}

// --- Editor --------------------------------------------------------------------

// Light syntax theme tuned to the docs palette (same as the other playgrounds).
const syntaxTheme = HighlightStyle.define([
  { tag: [t.keyword, t.modifier, t.operatorKeyword, t.self, t.null], color: '#b45309' },
  { tag: [t.string, t.special(t.string)], color: '#0f766e' },
  { tag: [t.number, t.bool, t.atom], color: '#9a3412' },
  { tag: [t.lineComment, t.blockComment, t.docComment], color: '#a8a29e', fontStyle: 'italic' },
  { tag: [t.propertyName, t.attributeName], color: '#1c1917' },
  { tag: [t.invalid], color: '#b91c1c' },
])

const editorTheme = EditorView.theme({
  '&': {
    height: '100%',
    fontSize: '13px',
    background: 'transparent',
    color: '#292524',
  },
  '&.cm-focused': {
    outline: 'none',
  },
  '.cm-scroller': {
    fontFamily: "ui-monospace, 'SF Mono', 'Cascadia Code', Menlo, Consolas, monospace",
    lineHeight: '1.6',
  },
  '.cm-content': {
    padding: '14px 16px 16px 6px',
    caretColor: '#b45309',
  },
  '.cm-cursor, .cm-dropCursor': {
    borderLeftColor: '#b45309',
  },
  '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection': {
    background: 'rgba(180, 83, 9, 0.15)',
  },
  '.cm-gutters': {
    background: 'transparent',
    borderRight: 'none',
    color: '#a8a29e',
  },
  '.cm-lineNumbers .cm-gutterElement': {
    paddingLeft: '14px',
    paddingRight: '10px',
    minWidth: '2em',
    textAlign: 'right',
  },
})

onMounted(async () => {
  view.value = new EditorView({
    parent: editorEl.value!,
    state: EditorState.create({
      doc: SAMPLE_CODE,
      extensions: [
        lineNumbers(),
        history(),
        drawSelection(),
        dropCursor(),
        indentOnInput(),
        syntaxHighlighting(syntaxTheme, { fallback: true }),
        EditorView.lineWrapping,
        editorTheme,
        javascriptMode(),
        keymap.of([
          // Cmd/Ctrl+Enter renders immediately instead of waiting for the debounce.
          {
            key: 'Mod-Enter',
            run: () => {
              void render()
              return true
            },
          },
          ...defaultKeymap,
          ...historyKeymap,
          indentWithTab,
        ]),
        EditorView.updateListener.of((update) => {
          if (update.docChanged) schedule()
        }),
      ],
    }),
  })

  try {
    // Inter loads from the docs site's static assets (docs/public/fonts);
    // code falls back to the builtin mono alias (Courier).
    const face = (name: string) => fetch(`/fonts/${name}`).then((r) => r.arrayBuffer())
    fonts = await useFonts(
      { body: 'inter' },
      {
        files: {
          inter: {
            regular: await face('Inter-Regular.ttf'),
            bold: await face('Inter-Bold.ttf'),
            italic: await face('Inter-Italic.ttf'),
            boldItalic: await face('Inter-BoldItalic.ttf'),
          },
        },
      },
    )
  } catch (err) {
    console.error('editing playground: font loading failed, falling back to builtins', err)
  }

  sampleBytes = await makeSamplePdf()
  await render()
})

onBeforeUnmount(() => {
  view.value?.destroy()
  if (objectUrl) URL.revokeObjectURL(objectUrl)
  if (timer) clearTimeout(timer)
})
</script>

<template>
  <div class="flex min-h-0 w-full h-screen flex-1 flex-col overflow-hidden bg-paper">
    <header class="flex w-full items-center border-b border-ink/10 justify-between px-4">
     <Breadcrumbs :title="'editing'" />
     <div class="flex items-center gap-2  py-2">
       <span
         class="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 font-mono text-[11px] uppercase tracking-[0.06em] whitespace-nowrap"
         :class="error
           ? 'border-[rgba(185,28,28,0.35)] bg-[rgba(185,28,28,0.05)] text-[#b91c1c]'
           : 'border-ink/15 text-muted'"
         :title="error"
       >
         <span class="h-1.5 w-1.5 rounded-full" :class="error ? 'bg-red-500' : 'bg-green-500'"></span>
         {{ badge }}
       </span>
       <label
         class="cursor-pointer rounded-md border border-solid border-ink/15 px-2.5 py-1.5 font-mono text-xs uppercase tracking-[0.2em] text-ink no-underline transition-colors duration-120 hover:border-ink hover:bg-ink hover:text-paper"
         :title="fileName"
       >Load PDF
         <input type="file" accept="application/pdf,.pdf" class="hidden" @change="loadFile" />
       </label>
       <button
         type="button"
         class="cursor-pointer rounded-md border border-solid border-ink/15 px-2.5 py-1.5 font-mono text-xs uppercase tracking-[0.2em] text-ink no-underline transition-colors duration-120 hover:border-ink hover:bg-ink hover:text-paper"
         @click="reset"
       >Reset</button>
       <a
         class="rounded-md border border-solid border-ink bg-ink px-2.5 py-1.5 font-mono text-xs uppercase tracking-[0.2em] text-paper no-underline transition-colors duration-120 hover:border-black hover:bg-black"
         :href="downloadHref"
         download="edited.pdf"
       >Download PDF</a>
     </div>
    </header>

    <main class="relative flex min-h-0 flex-1">
      <div class="relative flex min-h-0 flex-1">
        <div class="flex w-1/2 min-w-0 flex-col border-r border-ink/10">
          <div class="flex h-9 flex-none items-center gap-2 border-b border-ink/10 px-4">
            <span class="h-1.5 w-1.5 bg-accent"></span>
            <span class="font-mono text-[10px] uppercase tracking-[0.14em] text-muted">Overlay code</span>
            <span class="ml-auto font-mono text-[10px] uppercase tracking-[0.14em] text-[#a8a29e]">JavaScript</span>
          </div>
          <div
            ref="editorEl"
            class="min-h-0 flex-1 focus-within:shadow-[inset_0_0_0_1px_rgba(180,83,9,0.3)]"
          ></div>
        </div>
        <div class="flex w-1/2 bg-paper2 min-w-0 flex-col">
          <div class="flex h-9 flex-none  items-center gap-2 border-b border-ink/10 px-4">
            <span class="h-1.5 w-1.5 bg-ink"></span>
            <span class="font-mono text-[10px] uppercase tracking-[0.14em] text-muted">Proof</span>
            <span class="ml-auto font-mono text-[10px] uppercase tracking-[0.14em] text-[#a8a29e]">{{ fileName }}</span>
          </div>
          <iframe
            ref="frameEl"
            class="min-h-0 flex-1 bg-paper2"
            title="PDF preview"
          ></iframe>
        </div>
        <p
          v-if="error"
          class="absolute bottom-0 left-0 z-10 m-0 w-1/2 overflow-hidden whitespace-nowrap border-t border-[rgba(185,28,28,0.3)] bg-[rgba(185,28,28,0.05)] px-3.5 py-2 font-mono text-xs text-ellipsis text-[#b91c1c]"
          :title="error"
        >{{ error.split('\n')[0] }}</p>
      </div>
    </main>
  </div>
</template>
